---
plugin: aws_ec2
# aws_access_key: <YOUR-AWS-ACCESS-KEY-HERE>
# aws_secret_key: <YOUR-AWS-SECRET-KEY-HERE>
regions:
  - ap-south-1
keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type
  