---
- name: Install python3, docker, docker-compose
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - python3
          - docker
        update_cache: yes
        state: present

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-darwin-x86_64
        dest: /usr/local/bin/docker-compose
        mode: +x

    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started

    - name: Install docker python module
      pip:
        name:
          - docker
          - docker-compose